// <auto-generated />
using System;
using Hospital_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Database
{
    [DbContext(typeof(ClinicContext))]
    partial class ClinicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Models.AdminAssistantShift", b =>
                {
                    b.Property<int>("AdminShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminShiftID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminShiftId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("HoursWorked")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasComputedColumnSql("timestampdiff(HOUR,`ClockInTime`,`ClockOutTime`)", false);

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.HasKey("AdminShiftId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "AdminID");

                    b.HasIndex(new[] { "ShiftId" }, "ShiftID");

                    b.ToTable("AdminAssistant_Shifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.AdministrativeAssistant", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("'20.00'");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AdminId")
                        .HasName("PRIMARY");

                    b.ToTable("Administrative_Assistant");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Status")
                        .HasColumnType("enum('Booked','Cancelled','Arrived','Checked In','Checked Out','LWT','No-Show')");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("AppointmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID");

                    b.HasIndex(new[] { "NurseId" }, "NurseID");

                    b.HasIndex(new[] { "PatientId" }, "PatientID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.DiagnosticTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("ClinicalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<DateTime?>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int")
                        .HasColumnName("VisitID");

                    b.HasKey("TestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID")
                        .HasDatabaseName("DoctorID1");

                    b.HasIndex(new[] { "VisitId" }, "VisitID");

                    b.ToTable("DiagnosticTest");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DoctorId")
                        .HasName("PRIMARY");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.DoctorsShift", b =>
                {
                    b.Property<int>("DoctorsShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Doctors_ShiftID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorsShiftId"));

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.HasKey("DoctorsShiftId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID")
                        .HasDatabaseName("DoctorID2");

                    b.HasIndex(new[] { "ShiftId" }, "ShiftID")
                        .HasDatabaseName("ShiftID1");

                    b.ToTable("Doctors_Shifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Fee", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<DateTime?>("FeeDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FeeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID")
                        .HasDatabaseName("DoctorID3");

                    b.HasIndex(new[] { "PatientId" }, "PatientID")
                        .HasDatabaseName("PatientID1");

                    b.ToTable("Fee");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ManagerId")
                        .HasName("PRIMARY");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Nurse", b =>
                {
                    b.Property<int>("NurseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NurseId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("'35.00'");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("NurseId")
                        .HasName("PRIMARY");

                    b.ToTable("Nurse");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.NurseShift", b =>
                {
                    b.Property<int>("NurseShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NurseShiftID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NurseShiftId"));

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("HoursWorked")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasComputedColumnSql("timestampdiff(HOUR,`ClockInTime`,`ClockOutTime`)", false);

                    b.Property<int>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.HasKey("NurseShiftId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NurseId" }, "NurseID")
                        .HasDatabaseName("NurseID1");

                    b.HasIndex(new[] { "ShiftId" }, "ShiftID")
                        .HasDatabaseName("ShiftID2");

                    b.ToTable("NurseShifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HealthCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PrimaryMemberId")
                        .HasColumnType("int")
                        .HasColumnName("PrimaryMemberID");

                    b.Property<string>("Relationship")
                        .HasColumnType("enum('Husband','Wife','Son','Daughter','Father','Mother','Other')");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('Enrolled','Walk-in')");

                    b.HasKey("PatientId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID")
                        .HasDatabaseName("DoctorID4");

                    b.HasIndex(new[] { "HealthCardNo" }, "HealthCardNo")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "PhoneNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "PrimaryMemberId" }, "PrimaryMemberID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.PatientVital", b =>
                {
                    b.Property<int>("VitalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VitalsID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VitalsId"));

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("Height")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("Recorded_At")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VisitsId")
                        .HasColumnType("int")
                        .HasColumnName("VisitsID");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VitalsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NurseId" }, "NurseID")
                        .HasDatabaseName("NurseID2");

                    b.HasIndex(new[] { "VisitsId" }, "VisitsID");

                    b.ToTable("Patient_Vitals");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    b.Property<int?>("VisitsId")
                        .HasColumnType("int")
                        .HasColumnName("VisitsID");

                    b.HasKey("PrescriptionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "DoctorID")
                        .HasDatabaseName("DoctorID5");

                    b.HasIndex(new[] { "ResultId" }, "ResultID");

                    b.HasIndex(new[] { "VisitsId" }, "VisitsID")
                        .HasDatabaseName("VisitsID1");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReferralID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ReferringDoctorId")
                        .HasColumnType("int")
                        .HasColumnName("ReferringDoctorID");

                    b.Property<int>("SpecialistDoctorId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialistDoctorID");

                    b.Property<int>("VisitId")
                        .HasColumnType("int")
                        .HasColumnName("VisitID");

                    b.HasKey("ReferralId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReferringDoctorId" }, "ReferringDoctorID");

                    b.HasIndex(new[] { "SpecialistDoctorId" }, "SpecialistDoctorID");

                    b.HasIndex(new[] { "VisitId" }, "VisitID")
                        .HasDatabaseName("VisitID1");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Secretary", b =>
                {
                    b.Property<int>("SecretaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecretaryID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecretaryId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("'25.00'");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SecretaryId")
                        .HasName("PRIMARY");

                    b.ToTable("Secretary");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.SecretaryShift", b =>
                {
                    b.Property<int>("SecretaryShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Secretary_ShiftID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecretaryShiftId"));

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("HoursWorked")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasComputedColumnSql("timestampdiff(HOUR,`ClockInTime`,`ClockOutTime`)", false);

                    b.Property<int>("SecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("SecretaryID");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.HasKey("SecretaryShiftId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecretaryId" }, "SecretaryID");

                    b.HasIndex(new[] { "ShiftId" }, "ShiftID")
                        .HasDatabaseName("ShiftID3");

                    b.ToTable("Secretary_Shifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("enum('Morning','Evening')");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId")
                        .HasName("PRIMARY");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.TestResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    b.Property<DateTime?>("ResultDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("TestID");

                    b.HasKey("ResultId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NurseId" }, "NurseID")
                        .HasDatabaseName("NurseID3");

                    b.HasIndex(new[] { "TestId" }, "TestID");

                    b.ToTable("TestResult");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.Property<int>("VisitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VisitsID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitsId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<DateTime?>("CheckinTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("Checkin_Time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("Checkout_Time");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .HasColumnType("text");

                    b.HasKey("VisitsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AppointmentId" }, "AppointmentID");

                    b.HasIndex(new[] { "PatientId" }, "PatientID")
                        .HasDatabaseName("PatientID2");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.AdminAssistantShift", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.AdministrativeAssistant", "Admin")
                        .WithMany("AdminAssistantShifts")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("adminassistant_shifts_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Shift", "Shift")
                        .WithMany("AdminAssistantShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("adminassistant_shifts_ibfk_2");

                    b.Navigation("Admin");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("appointment_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .HasConstraintName("appointment_ibfk_3");

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("appointment_ibfk_1");

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.DiagnosticTest", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("DiagnosticTests")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("diagnostictest_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany("DiagnosticTests")
                        .HasForeignKey("VisitId")
                        .IsRequired()
                        .HasConstraintName("diagnostictest_ibfk_1");

                    b.Navigation("Doctor");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.DoctorsShift", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("DoctorsShifts")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("doctors_shifts_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Shift", "Shift")
                        .WithMany("DoctorsShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("doctors_shifts_ibfk_2");

                    b.Navigation("Doctor");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Fee", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("Fees")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("fee_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany("Fees")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("fee_ibfk_1");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.NurseShift", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Nurse", "Nurse")
                        .WithMany("NurseShifts")
                        .HasForeignKey("NurseId")
                        .IsRequired()
                        .HasConstraintName("nurseshifts_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Shift", "Shift")
                        .WithMany("NurseShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("nurseshifts_ibfk_2");

                    b.Navigation("Nurse");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("patient_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Patient", "PrimaryMember")
                        .WithMany("InversePrimaryMember")
                        .HasForeignKey("PrimaryMemberId")
                        .HasConstraintName("patient_ibfk_2");

                    b.Navigation("Doctor");

                    b.Navigation("PrimaryMember");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.PatientVital", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Nurse", "Nurse")
                        .WithMany("PatientVitals")
                        .HasForeignKey("NurseId")
                        .IsRequired()
                        .HasConstraintName("patient_vitals_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visits")
                        .WithMany("PatientVitals")
                        .HasForeignKey("VisitsId")
                        .IsRequired()
                        .HasConstraintName("patient_vitals_ibfk_2");

                    b.Navigation("Nurse");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("prescription_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.TestResult", "Result")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ResultId")
                        .HasConstraintName("prescription_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visits")
                        .WithMany("Prescriptions")
                        .HasForeignKey("VisitsId")
                        .HasConstraintName("prescription_ibfk_3");

                    b.Navigation("Doctor");

                    b.Navigation("Result");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Referral", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Doctor", "ReferringDoctor")
                        .WithMany("ReferralReferringDoctors")
                        .HasForeignKey("ReferringDoctorId")
                        .IsRequired()
                        .HasConstraintName("referral_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.Doctor", "SpecialistDoctor")
                        .WithMany("ReferralSpecialistDoctors")
                        .HasForeignKey("SpecialistDoctorId")
                        .IsRequired()
                        .HasConstraintName("referral_ibfk_3");

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany("Referrals")
                        .HasForeignKey("VisitId")
                        .IsRequired()
                        .HasConstraintName("referral_ibfk_1");

                    b.Navigation("ReferringDoctor");

                    b.Navigation("SpecialistDoctor");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.SecretaryShift", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Secretary", "Secretary")
                        .WithMany("SecretaryShifts")
                        .HasForeignKey("SecretaryId")
                        .IsRequired()
                        .HasConstraintName("secretary_shifts_ibfk_1");

                    b.HasOne("Hospital_Management_System.Models.Shift", "Shift")
                        .WithMany("SecretaryShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("secretary_shifts_ibfk_2");

                    b.Navigation("Secretary");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.TestResult", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Nurse", "Nurse")
                        .WithMany("TestResults")
                        .HasForeignKey("NurseId")
                        .IsRequired()
                        .HasConstraintName("testresult_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.DiagnosticTest", "Test")
                        .WithMany("TestResults")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("testresult_ibfk_1");

                    b.Navigation("Nurse");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Appointment", "Appointment")
                        .WithMany("Visits")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("visits_ibfk_2");

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("visits_ibfk_1");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.AdministrativeAssistant", b =>
                {
                    b.Navigation("AdminAssistantShifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.DiagnosticTest", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DiagnosticTests");

                    b.Navigation("DoctorsShifts");

                    b.Navigation("Fees");

                    b.Navigation("Patients");

                    b.Navigation("Prescriptions");

                    b.Navigation("ReferralReferringDoctors");

                    b.Navigation("ReferralSpecialistDoctors");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Nurse", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("NurseShifts");

                    b.Navigation("PatientVitals");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Fees");

                    b.Navigation("InversePrimaryMember");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Secretary", b =>
                {
                    b.Navigation("SecretaryShifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Shift", b =>
                {
                    b.Navigation("AdminAssistantShifts");

                    b.Navigation("DoctorsShifts");

                    b.Navigation("NurseShifts");

                    b.Navigation("SecretaryShifts");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.TestResult", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.Navigation("DiagnosticTests");

                    b.Navigation("PatientVitals");

                    b.Navigation("Prescriptions");

                    b.Navigation("Referrals");
                });
#pragma warning restore 612, 618
        }
    }
}
